### ISSUE TITLE
ECS ComponentSystem OnUpdate() is not getting called on Android.

### ISSUE THREAD

**Issue by levey-lee** [Unity-Technologies/EntityComponentSystemSamples#60] opened 2018-09-19 02:46 UTC
ECS preview 8

I have a project that is pure ECS based. Everything works fine with debug logs in the editor for Android, but none of the **ComponentSystem.OnUpdate()** is getting called while I run it on my cellphone.

I've checked **ScriptBehaviourManager.Update()** and **ScriptBehaviourManager.Update()** but they were not getting called either. Monobehaviors Update() method works fine.

I'm making a RTS game prototype where I disabled the default world and automatic bootstrap, but I don't have any hybrid injections going on. Everything except for the main camera is ECS based.

Any advice will be appreciated.

**Comment by amechtley** [comment] 2018-09-19 11:06
Hi there! This sounds like another open case we have right now.

The issue is related to code stripping when building to IL2CPP. Because there are no references to the Unity.Entities.Hybrid assembly, the AutomaticWorldBootstrap that builds the ECS player loop gets stripped out. We will ultimately solve this by shuffling some stuff around into the proper assemblies, but in the meantime you can work around this by either:

1. Have a GameObjectEntity component on something in your scene
2. Add the Unity.Entities.Hybrid assembly to a link.xml file in your project (see https://docs.unity3d.com/Manual/IL2CPP-BytecodeStripping.html)

**Comment by levey-lee** [comment] 2018-09-19 18:00
I was building it using Mono. Do I have to choose IL2CPP for ECS to work? I've tried to build using IL2CPP but it didn't work out. An error message popped up say my desktop directory is not found, which is kind of weird though.

Back to the point, I've tried building it using Mono with a GameObjectEntity component attached to a cube, the problem still presents. Do I have to choose IL2CPP?

**Comment by amechtley** [comment] 2018-09-19 18:02
No this sounds like it should work. Would you mind filing a bug report and pasting the case number here please?

**Comment by levey-lee** [comment] 2018-09-19 22:04
I just dived into the code and found the problem.  In **World.cs**, there is a private method signature is  **private ScriptBehaviourManager CreateManagerInternal(Type type, int capacity, object[] constructorArguments)**

In the first try block in that function, there's a line **manager = Activator.CreateInstance(type, constructorArguments) as ScriptBehaviourManager;** This line will fail on Android device if we do **World.GetOrCreateManager<Unity.Rendering.MeshInstanceRendererSystem>();**  Then in the catch block right after it an exception will be thrown. I guess in the editor, we would know if there's an exception being thrown, but there's no message at all if we run it on Android device, and the system will fail silently.
 
Hopefully that helps.

**Comment by leethomason** [comment] 2019-06-04 22:20
This is tracked internally as 1160294. Closing this external issue - thanks for the info!

**Closed by leethomason** 2019-06-04 22:20 UTC
Labels: bug
