### ISSUE TITLE
Missing file error

### ISSUE THREAD

**Issue by AaronCBeyondImagination** [Unity-Technologies/EntityComponentSystemSamples#49] opened 2018-08-11 12:41 UTC
Hi folks

Seems I'm getting
_Assembly has reference to non-existent assembly 'Unity.Postprocessing.Runtime'_

Error over and over. What download is this in? I've just installed
"ScriptableRenterPipeline-Master"

Thanks!

**Comment by IsaiahKelly** [comment] 2018-08-23 20:10
Post-processing is really outside the scope of this repository so you're unlikely to get any help here. Much better to post such issues in the Unity [forums](https://forum.unity.com/forums/image-effects.96/) or [answers](https://answers.unity.com/index.html) sections instead. You should also provide more details so other can better guess what might be the cause. For example:

- Which version of Unity are you using?
- How did you install the package?

"ScriptableRenterPipeline-Master" would seem to suggest you just downloaded a zip of the repository and imported that into your project. This is probably the issue. You should delete that and install it through the Package Manager instead. I think you need Unity 2017.4 or newer to get access to the Package Manager, but using the latest version of Unity (2018.2) is recommended. 


Note: you can close this issue by clicking on the close button at the bottom.

**Comment by amechtley** [comment] 2018-09-20 19:40
Hi there! Sorry no one on our side got back to you on this issue. I hope you're no longer still having the problem. I'm not sure where it would have arisen from the entities package, but your project probably needed the Postprocessing package, which you can install via the Package Manager window in the Editor. I'll go ahead and close this issue, but feel free to reopen if it is still a problem.

**Closed by amechtley** 2018-09-20 19:40 UTC
